#!/bin/bash
#PBS -N parallelpaintingvaka  # Job name
#PBS -q edu_shared            # Queue name
#PBS -l nodes=4               # Request 4 nodes and 1 processor per node
#PBS -l walltime=00:01:00     # Maximum walltime for the job
#PBS -o mandelbrot.otxt       # Output file name
#PBS -e mandelbrot.etxt       # Error file name
#PBS -V                       # Export all environment variables to the job

cd $PBS_O_WORKDIR             # Change to the job submission directory
module load OpenMPI           # Load the OpenMPI module
mpirun ./mandelbrot-mpi       # Execute the MPI program with 4 processes